// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0IcpROcCMjvbhJ6pBXG1iHE3rR-FSRpM',
    appId: '1:13898217086:web:354e6aef0b0cb3bb788a2f',
    messagingSenderId: '13898217086',
    projectId: 'stationary-flutter',
    authDomain: 'stationary-flutter.firebaseapp.com',
    storageBucket: 'stationary-flutter.appspot.com',
    measurementId: 'G-QDRHJ1HLGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCGlXn1N_APB-LUUZ0pbV6daMtaGmPWsQ',
    appId: '1:13898217086:android:859febf5a16e6681788a2f',
    messagingSenderId: '13898217086',
    projectId: 'stationary-flutter',
    storageBucket: 'stationary-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8jQwerLYS3oYnBbWD_GdhWNIqenoHbzM',
    appId: '1:13898217086:ios:c5a650bc8cf9cc6d788a2f',
    messagingSenderId: '13898217086',
    projectId: 'stationary-flutter',
    storageBucket: 'stationary-flutter.appspot.com',
    iosBundleId: 'com.example.subhashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8jQwerLYS3oYnBbWD_GdhWNIqenoHbzM',
    appId: '1:13898217086:ios:b2a5916ccfa1e360788a2f',
    messagingSenderId: '13898217086',
    projectId: 'stationary-flutter',
    storageBucket: 'stationary-flutter.appspot.com',
    iosBundleId: 'com.example.subhashApp.RunnerTests',
  );
}
